### ISSUE TITLE
How could I use word_freqs properly?

### ISSUE THREAD

**Issue by 7633** [explosion/spacy-dev-resources#23]
I have corpus with raw txt files, but script requires freqs_dir and output_loc, that If I'm not mistaken is files, actually not path. 
Please provide usage of this script for me.

**Comment by mosynaq** [comment]
Thanks, @7633! I have the same problem and question!
# First Problem/Question
 I have a huge file as a corpus. I mean it is only one file. But the official documents in [here](https://spacy.io/usage/adding-languages#training) imply that there should be more than one file:

> 1. The number of times the word occurred in your language sample.
> 2. **The number of distinct documents** the word occurred in.
> 3. The word itself.

- Should my corpus consist of more than one file?

Considering, again, the official doc, saying:
> Note that your corpus should not be preprocessed (i.e. you need punctuation for example).

- Should it be in any specific format?

# Second Problem/Question
The command I issue, after doing `cd` to the path with `word_freqs.py` and my coupus `fa_edited.txt`, is:
`$python3 word_freqs.py  en fa_edited.txt freq out -n 8 -s`
But I get the following error:
```bash
$ python3 word_freqs.py  en fa_edited.txt freq out -n 8 -s
Traceback (most recent call last):
  File "word_freqs.py", line 93, in <module>
    plac.call(main)
  File "/home/MYNAME/PythonProjects/AddPersianToSpacy/spacy2_env/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/MYNAME/PythonProjects/AddPersianToSpacy/spacy2_env/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "word_freqs.py", line 82, in main
    if not output_path.exists() or not skip_existing:
  File "/usr/lib/python3.5/pathlib.py", line 1306, in exists
    self.stat()
  File "/usr/lib/python3.5/pathlib.py", line 1126, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 36] File name too long: 'freq/معاون سازمان سنجش آموزش کشور با تشریح جزئیات کنکور کارشناسی ارشد  از صدور  هزار و  کارت ورود به جلسه این آزمون خبر داد و گفت: کارتهای ورود به جلسه آزمون از  بهمن ماه بر روی سایت سازمان سنجش آموزش کشور قرار می گیرد. ابراهیم خدایی در گفتگو با خبرنگار مهر افزود: در آزمون کارشناسی ارشد ناپیوسته داخل سال  برای  کد رشته شامل  کد رشته امتحانی در گروه علوم انسانی،  کد رشته امتحانی در گروه علوم پایه،  کد رشته در گروه فنی ومهندسی،  کد رشته در گروه کشاورزی،  کد رشته در گروه هنر،  کد رشته در گروه علوم پزشکی ( فقط برای دانشگاه تربیت مدرس)،  کد رشته در گروه دامپزشکی دانشجو پذیرش می شود. هزار و  داوطلب در کنکور کارشناسی ارشد ثبت نام کرده اند وی اظهار داشت: ثبت نام در آزمون برای  کد رشته امتحانی از  کد رشته امتحانی و همچنین اولین مرحله آزمون پانزدهمین المپیاد علمی دانشجویی کشور بر اساس برنامه زمانی به صورت متمرکز و از طریق شبکه اینترنت انجام شد. در آزمون  کد رشته و اولین مرحله المپیاد  هزار و  داوطلب ثبت نام کرده اند که از این تعداد  هزار و  نفر زن و  هزار و  نفر مرد هستند. هزار و  نفر متقاضی شرکت در آزمون کد رشته امتحانی دوم کارشناسی ارشد معاون سازمان سنجش آموزش کشور به مهر گفت: نظر به اینکه بر اساس ضوابط داوطلبان می توانستند در صورت واجد شرایط و علاقه مند بودن از میان  کد رشته امتحانی شناور مندرج در دفترچه راهنما یکی از کد رشته های مذکور را به عنوان کد رشته امتحانی دوم علاوه بر کد رشته امتحانی اصلی انتخاب کنند  هزار و  نفر نیز متقاضی شرکت در آزمون کد رشته امتحانی دوم شده اند. جزئیات توزیع کارت آزمون کارشناسی ارشد وی با اشاره توزیع کارت آزمون کارشناسی ارشد  اضافه کرد: با توجه به اینکه آزمون هر کد رشته به طور جداگانه برگزار می شود و هر داوطلب برای شرکت در آزمون هر کد رشته باید کارت مربوط را داشته باشد برای داوطلبانی که در دو کد رشته امتحانی ثبت نام کرده اند دو کارت ورود به جلسه صادر می شود. صدور  هزار و  کارت ورود به جلسه آزمون خدایی ادامه داد: از این رو  هزار و  کارت ورود به جلسه آزمون صادر خواهد شد که از این تعداد  هزار و  کارت مربوط به خواهران و  هزار و  کارت مربوط به برادران می شود. توزیع کارت ورود به جلسه آزمون ارشد از  بهمن ماه وی ادامه داد: بر اساس برنامه زمانی کارت ورود به جلسه آزمون از طریق شبکه اینترنت سازمان سنجش از  بهمن ماه تا  بهمن ماه در اختیار داوطلبان قرار می گیرد. معاون سازمان سنجش آموزش کشور گفت: اطلاعیه سازمان سنجش آموزش کشور در رابطه با توزیع کارت اینترنتی در نشریه دوشنبه  بهمن ماه و  بهمن ماه منتشر و همزمان بر روی سایت قرار داده می شود. همچنین به منظور آشنایی داوطلبان با نحوه برگزاری آزمون و نحوه علامتگذاری در پاسخنامه برگه راهنمای شرکت در آزمون از  بهمن ماه بر روی سایت سازمان سنجش قرار می گیرد تا داوطلبان با مراجعه به سایت سازمان نسبت به مطالعه آن اقدام کنند. میزان تاثیر معدل در کنکور کارشناسی ارشد خدایی در زمینه تاثیر معدل در کنکور کارشناسی ارشد به مهر گفت: معدل کارشناسی در کنکور کارشناسی ارشد به میزان  درصد تأثیرگذار خواهد بود. وی گفت: این  درصد در کنکور امسال نیز مانند سال گذشته به صورت تراز شده اعمال می شود. معاون سازمان سنجش درباره زمان برگزاری این کنکور نیز به مهر گفت: آزمون کارشناسی ارشد سال  در صبح و بعدازظهر ،  و  بهمن ماه برگزار می شود.'
```
What is the problem with my training? Is it the corpus, comamnd, or `word_freqs.py`?

p.s.
The problem looks to be from the  `word_freqs.py`. Since it is Not my script, I don't know how to correct it. It seems that the scrpts tries  to create a file with a very long name which is not possible.

# My Environment
* **Python version:** 3.5.2
* **Models:** en, en_default
* **spaCy version:** 2.0.3
* **Platform:** Linux-4.11.0-14-generic-x86_64-with-LinuxMint-18.2-sonya

**Comment by schafferer** [comment]
I'm having this exact problem as well. Any news on some better documentation?
