### ISSUE TITLE
python -m spacy model is not work on spaCy 2.0

### ISSUE THREAD

**Issue by asachanmanchoi** [explosion/spacy-dev-resources#24]
Hey guys,

I'm trying to create a new model. But I found that the "model" option is removed on spacy 2.0. 

`python -m spacy **model** <lang> ./data/model/<lang>/spacy_model ./data/model/<lang>/<lang>_wiki.freqs ./data/model/<lang>/brown/paths ./data/model/<lang>/<lang>_wiki.word2vec.bz2
`

In spacy cli directory, it is no model.py file found. 

How to train a my new own model in spacy 2.0?
Thanks

**Comment by mosynaq** [comment]
[As the official docs say](https://spacy.io/api/cli#init-model), it is replaced by `python -m spacy init-model ...`, which is still buggy.

### Here is what I write:
`python3 -m spacy init-model fa fa_vec_model ./freqs/ -c ./clusters -v ./vectors/`
### This is what I get:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 257, in populate_from
    a = Annotation.from_(ann)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 91, in from_
    return cls(*obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 78, in __init__
    assert abbrev is None, abbrev
AssertionError: f
```
