### ISSUE TITLE
Issue in wiki2txt

### ISSUE THREAD

**Issue by azarezade** [explosion/spacy-dev-resources#27]
I have problem extracting text data from wiki.xml file using `wiki2txt.py`. Specifically, when I run 
```
>>> fab -f vocab/fabfile build_wiki_vocab:fa
```
then in the middle of execution in returns the following exception:
```
[localhost] local: mkdir -p ./data/corpora/fa
[localhost] local: mkdir -p ./data/corpora/fa/wiki
[localhost] local: python ./corpus-utils/wiki2txt.py ./data/corpora/fa/fa_wiki.xml.bz2 ./data/corpora/fa/wiki fa
1143424it [15:40, 1216.33it/s]Traceback (most recent call last):
  File "./corpus-utils/wiki2txt.py", line 80, in <module>
    plac.call(main)
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "./corpus-utils/wiki2txt.py", line 73, in main
    for id, title, content in tqdm(reader):
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/textacy/corpora/wiki_reader.py", line 158, in __iter__
    content = bytes_to_unicode(content, errors='ignore')
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/textacy/compat.py", line 17, in bytes_to_unicode
    return unicode_type(b, encoding=encoding, errors=errors)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Fatal error: local() encountered an error (return code 1) while executing 'python ./corpus-utils/wiki2txt.py ./data/corpora/fa/fa_wiki.xml.bz2 ./data/corpora/fa/wiki fa'

Aborting.
```

**Comment by azarezade** [comment]
It seems there was some problem regarding #28, which caused `None` content in main function of `wiki2txt.py`:
```
def main(dump_path, out_dir, lang, cleaned=True):
    reader = WikiReader(dump_path)
    nlp = spacy.load(lang, parser=None, tagger=None)
    for id, title, content in tqdm(reader):
        text_content = extract_text(content, nlp, cleaned)
        if text_content:
            write_file(id, out_dir, text_content, title)
```
